inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-sorbet
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Naming/FileName:
  Enabled: true

Style/StderrPuts:
  Enabled: true
